server:
  servlet:
    context-path:
  port: 8080

spring:
  application:
    name: Ecomm Gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: '*'
            allowed-methods: GET, POST, PUT, DELETE, PATCH
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      observation-enabled: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - url: /api
        name: 

management:
  server:
    port: ${server.port}
  endpoints:
    web:
      exposure:
        include: info, health, httptrace, loggers, metrics, threaddump
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      show-components: always
  tracing:
    enabled: true
    sampling:
      probability: 1.0



ecomm:
  service:
    tracing:
      url: http://localhost:4318/v1/traces
    authentication:
      scope: mobile
      enabled: true
      jwt:
        secret: Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=
    forward: http://localhost:9090
    users:
      baseUri: http://localhost:9090
