server:
  servlet:
    context-path:
  port: 8080

spring:
  boot:
    admin:
      client:
        # Cloud Native Spring Admin Server is running
        url: http://localhost:9090
  application:
    name: gateway-${ecomm.service.gateway.forward-api-name}
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: '*'
            allowed-methods: GET, POST, PUT, DELETE, PATCH
  kafka:
    bootstrap-servers: localhost:9091,localhost:9092,localhost:9093
    properties:
      security:
        protocol: PLAINTEXT
      sasl:
        mechanism: GSSAPI
        jaas:
          config:
    listener:
      observation-enabled: true
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: true
      group-id: gateway-${ecomm.service.gateway.forward-api-name}
      max-poll-records: 100
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
      observation-enabled: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      observation-enabled: true
  cache:
    type: redis
    redis:
      cache-null-values: true
      use-key-prefix: true
      key-prefix: ECOMM-GATEWAY
      time-to-live: 5000
  data:
    redis:
      host: localhost
      port: 6379
      ssl:
        enabled: false
      connectTimeout: 5000
      timeout: 1000

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - url: /api
        name: 

management:
  server:
    port: ${server.port}
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      show-components: always
  info:
    git:
      mode: full
  health:
    ratelimiters:
      enabled: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
      timeout: 1s
      compression: GZIP
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
logging:
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%-5p) [${spring.application.name}] [%clr(%15.15t){faint}] [%clr(%32X{traceId}-%16X{spanId}){blue}] %clr(%40.40logger{5.10}:%-4L){cyan} : %m %n'
  level:
    io.oigres.ecomm.gateway: INFO
    # Avoid kafka verbose INFO logging
    org.apache.kafka.clients.admin.AdminClientConfig: WARN
    org.apache.kafka.common.utils.AppInfoParser: WARN
    org.apache.kafka.common.metrics.Metrics: WARN
    org.apache.kafka.clients.consumer.ConsumerConfig: WARN
    org.apache.kafka.clients.producer.ProducerConfig: WARN

ecomm:
  service:
    authentication:
      scope: ${ecomm.service.gateway.forward-api-name}
      enabled: true
      jwt:
        secret: Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=
    gateway:
      forward-api-name: admin
      forward: http://localhost:5051
      auth-server-uri: http://localhost:6061
    limiter:
      topics:
        incoming-request:
          name: incoming-request-topic
          partitions: 100
          replication-factor: 2
        blacklisted-users:
          name: blacklisted-users-topic
          concurrency: 10
