name: CI
on:
  push:
    branches:
    - '**'
    
jobs:

  build-app:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4.2.2
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Download dependencies
        run: |
          pwd
          ls -l
          export VERSION=`mvn help:evaluate -Dexpression=project.version -q -DforceStdout`
          echo -e "VERSION=$VERSION"
          export USERS_API_ARTIFACT_ID=`curl -L -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" https://api.github.com/repos/sjexpos/ecomm-users-service/actions/artifacts | jq '.artifacts[] | "\(.id) \(.name)"' | tr -d '"' | grep users-service-api | head -n 1 | awk '{print $1}'`
          echo -e "artifact=$USERS_API_ARTIFACT_ID"
          curl -L -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" https://api.github.com/repos/sjexpos/ecomm-users-service/actions/artifacts/$USERS_API_ARTIFACT_ID/zip > users_api_artifact.zip
          unzip users_api_artifact.zip
          ls -l
          mvn install:install-file -Dfile=users-service-api-$VERSION.jar -DgroupId=io.oigres.ecomm -DartifactId=users-service-api -Dversion=$VERSION -Dpackaging=jar -DgeneratePom=true
          rm users-service-api-$VERSION.jar
          rm users_api_artifact.zip
          ls -l
          export USERS_SDK_ARTIFACT_ID=`curl -L -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" https://api.github.com/repos/sjexpos/ecomm-users-service/actions/artifacts | jq '.artifacts[] | "\(.id) \(.name)"' | tr -d '"' | grep users-service-sdk | head -n 1 | awk '{print $1}'`
          echo -e "artifact=$USERS_SDK_ARTIFACT_ID"
          curl -L -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" https://api.github.com/repos/sjexpos/ecomm-users-service/actions/artifacts/$USERS_SDK_ARTIFACT_ID/zip > users_sdk_artifact.zip
          unzip users_sdk_artifact.zip
          ls -l
          mvn install:install-file -Dfile=users-service-sdk-$VERSION.jar -DgroupId=io.oigres.ecomm -DartifactId=users-service-sdk -Dversion=$VERSION -Dpackaging=jar -DgeneratePom=true
          rm users-service-sdk-$VERSION.jar
          rm users_sdk_artifact.zip
          export LIMITER_MODEL_ARTIFACT_ID=`curl -L -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" https://api.github.com/repos/sjexpos/ecomm-limiter/actions/artifacts | jq '.artifacts[] | "\(.id) \(.name)"' | tr -d '"' | grep limiter-service-model | head -n 1 | awk '{print $1}'`
          echo -e "artifact=$LIMITER_MODEL_ARTIFACT_ID"
          curl -L -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" https://api.github.com/repos/sjexpos/ecomm-limiter/actions/artifacts/$LIMITER_MODEL_ARTIFACT_ID/zip > limiter_model_artifact.zip
          unzip limiter_model_artifact.zip
          ls -l
          mvn install:install-file -Dfile=limiter-service-model-$VERSION.jar -DgroupId=io.oigres.ecomm -DartifactId=limiter-service-model -Dversion=$VERSION -Dpackaging=jar -DgeneratePom=true
          rm limiter-service-model-$VERSION.jar
          rm limiter_model_artifact.zip
          export CACHE_LIB_ARTIFACT_ID=`curl -L -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" https://api.github.com/repos/sjexpos/ecomm-limiter/actions/artifacts | jq '.artifacts[] | "\(.id) \(.name)"' | tr -d '"' | grep cache-lib | head -n 1 | awk '{print $1}'`
          echo -e "artifact=$CACHE_LIB_ARTIFACT_ID"
          curl -L -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" https://api.github.com/repos/sjexpos/ecomm-limiter/actions/artifacts/$CACHE_LIB_ARTIFACT_ID/zip > cache_lib_artifact.zip
          unzip cache_lib_artifact.zip
          ls -l
          mvn install:install-file -Dfile=cache-lib-$VERSION.jar -DgroupId=io.oigres.ecomm -DartifactId=cache-lib -Dversion=$VERSION -Dpackaging=jar -DgeneratePom=true
          rm cache-lib-$VERSION.jar
          rm cache_lib_artifact.zip
      - run: mvn --batch-mode --update-snapshots install
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload artifacts
        id: upload-compiled-sources
        uses: actions/upload-artifact@v4.3.3
        with:
          name: compiled-sources
          path: ./
    outputs:
      compiled-sources-artifact-id: ${{ steps.upload-compiled-sources.outputs.artifact-id }}

  build-docker-image:
    name: Create docker image
    needs: [build-app]
    runs-on: ubuntu-latest
    steps:
      - name: Download compiled sources
        uses: actions/download-artifact@v4.1.7
        with:
          name: compiled-sources
          path: ./
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: Dockerfile
          platforms: linux/amd64
          push: false
          tags: sjexpos/ecomm-gateway:latest

  delete-unused-artifact:
    name: Delete unused artifact
    needs: [build-app, build-docker-image]
    runs-on: ubuntu-latest
    steps:
      - name: Delete Artifact
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.actions.deleteArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: ${{ needs.build-app.outputs.compiled-sources-artifact-id }}
            });

# mvn jacoco:prepare-agent jacoco:report surefire:test
