name: CI
on:
  push:
    branches: [ "**" ]
    
jobs:
  ci:
    name: ''
    uses: sjexpos/ecomm-cicd-actions/.github/workflows/app-ci.yaml@main
    secrets: inherit
    with:
      sonar_project_key: gateway
      sonar_project_name: Gateway
      docker_images: "['sjexposecomm/gateway']"

